version: "3.2"
services:
  balancer:
    image: nginx:latest
    container_name: balancer_container
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - tokenizer
      - tokenizer_replica
    networks:
      - nginx

  tokenizer:
    image: harand/tokenizer
    ports:
      - "7000:8000"
    networks:
      - nginx

  tokenizer_replica:
    image: harand/tokenizer
    ports:
      - "9000:8000"
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
