version: "3.2"
services:
  approver:
    image: harand/approver
    ports:
      - "7000:8000"

  database:
    image: postgres
    container_name: ${DATABASE_HOST}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    command: postgres -p ${DATABASE_PORT}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/1-create_tables.sql:ro

